name: EasyCommandAutofill
main: jasonwynn10\EasyCommandAutofill\Main
version: 1.0.7
api: 3.24.0
description: "A plugin which adds commands to the client's autofill by parsing usage messages"
author: "jasonwynn10"